# Generated by Django 4.0.3 on 2022-04-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='alimentacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='enfermedades',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
