# Generated by Django 4.0.3 on 2022-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_mascota_alimentacion_mascota_enfermedades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='alimentacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='enfermedades',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=50),
        ),
    ]
